export const SEARCH_TERMS: string[] = [
  "Actualités France",
  "Recettes de cuisine",
  "Météo",
  "Football",
  "Cinéma",
  "Santé",
  "Voyages",
  "Musique",
  "Technologies",
  "Mode",
  "Emploi",
  "Éducation",
  "Économie",
  "Politique",
  "Environnement",
  "Jeux vidéo",
  "Livres",
  "Sport",
  "Séries TV",
  "Art",
  "Science",
  "Histoire",
  "Animaux",
  "Automobile",
  "Bricolage",
  "Jardinage",
  "Beauté",
  "Bien-être",
  "Gastronomie",
  "Décoration",
  "Informatique",
  "Photographie",
  "Danse",
  "Théâtre",
  "Musées",
  "Astronomie",
  "Psychologie",
  "Philosophie",
  "Langues étrangères",
  "Yoga",
  "Méditation",
  "Écologie",
  "Recycling",
  "Énergies renouvelables",
  "Littérature",
  "Poésie",
  "Architecture",
  "Design",
  "Innovation",
  "Startups",
];
